### ISSUE TITLE
Entities for "return to grid" and "grid consumption"

### ISSUE THREAD

**Issue by Bullischorsch** [TenySmart/ModbusTCP2MQTT#6]
Hi,

I can't see entities for the items "return to grid" and "grid consumption" though it should be possible to configure, I think.
I have a sungrow sg10rt, also tried to choose model sg5kd, which makes no difference.

regards and thanks for your work

Georg

**Comment by nvx** [comment]
> I can't see entities for the items "return to grid" and "grid consumption" though it should be possible to configure, I think.

They come in as attributes on the entity. Unfortunately the energy monitoring stuff in Home Assistant can't make use of the attribute values directly, but it's easy enough to setup a template sensor in your config file to get them as separate entities which you can then use:

```
template:
  - sensor:
      - name: inverter_self_consumption_today
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        state: >
          {{ state_attr('sensor.inverter_energy_today', 'daily_energy_consumption')|float / 1000 }}
        availability: >
          {{ states('sensor.inverter_energy_today')!='unavailable' }}
      - name: grid_purchased_today
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        state: >
          {{ state_attr('sensor.inverter_energy_today', 'daily_purchased_energy') }}
        availability: >
          {{ states('sensor.inverter_energy_today')!='unavailable' }}
      - name: grid_exported_today
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        state: >
          {{ (state_attr('sensor.inverter_energy_today', 'daily_power_yield')|float - state_attr('sensor.inverter_energy_today', 'daily_energy_consumption')|float) / 1000 }}
        availability: >
          {{ states('sensor.inverter_energy_today')!='unavailable' }}
```
